<?php

########################################################################
# Extension Manager/Repository config file for ext: "pt_extbase"
#
# Auto generated by Extbase Kickstarter 2011-03-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Tools for Extbase development',
	'description' => 'Collection of tools for Extbase Extension development.',
	'category' => 'plugin',
	'author' => 'Michael Knoll,Daniel Lienert',
	'author_email' => 'knoll@punkt.de,lienert@punkt.de',
	'author_company' => 'punkt.de GmbH,punkt.de GmbH',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1-dev',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '1.3.0',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>