services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PunktDe\PtExtbase\:
    resource: '../Classes/*.php'

  PunktDe\PtExtbase\Utility\:
    resource: '../Classes/Utility/{HeaderInclusion}.php'

  PunktDe\PtExtbase\Logger\:
    resource: '../Classes/Logger'

  PunktDe\PtExtbase\Controller\:
    resource: '../Classes/Controller'

  PunktDe\PtExtbase\Lifecycle\:
    resource: '../Classes/Lifecycle'

  PunktDe\PtExtbase\State\:
    resource: '../Classes/State'
    public: true

  PunktDe\PtExtbase\Domain\Model\:
    resource: '../Classes/Domain/Model'
    public: true

  PunktDe\PtExtbase\Domain\Repository\:
    resource: '../Classes/Domain/Repository'
    public: true

  PunktDe\PtExtbase\State\Session\Storage\AdapterInterface:
    alias: PunktDe\PtExtbase\State\Session\Storage\NullStorageAdapter

  PunktDe\PtExtbase\Configuration\AbstractConfiguration:
    arguments:
      $settings: []

